name: Update BLS Data

on:
  schedule:
    # Run this workflow at 2:00 AM UTC on the 1st day of every month
    - cron: '0 2 1 * *'
  workflow_dispatch: # Allow manual trigger of the workflow

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # Specify the Python version compatible with your project

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Data Update Script
      run: |
        python bls_econ_project.py # Ensure this is the correct script to fetch and update BLS data

    - name: Commit and Push Changes
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git add .
        git commit -m "Automated data update for BLS data"
        git push origin main # Ensure 'main' matches your default branch name
