name: Update Data Automatically

on:
  schedule:
    # Runs at 12:00 AM on the 1st day of every month
    - cron: "0 0 1 * *"

  workflow_dispatch:  # Allows manual triggering of the workflow
    inputs:
      reason:
        description: 'Reason for manual run'
        required: false

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Fetch and update data
      run: |
        python app.py  # Modify if you have a specific data update script
        git config user.name "Your GitHub Username"
        git config user.email "your-email@example.com"
        git add .
        git commit -m "Automated data update"
        git push
